name: Validate source by running pre-commit hooks

on:
  pull_request:
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: pip install pre-commit
      # run on changed files only
      - run: git diff --name-only -r HEAD^1 HEAD | xargs pre-commit run --files
